# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rootxploiter
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-node-express
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    DEBUG: ${env:DEBUG, 0}
    DATABASE_URL: ${env:DATABASE_URL, "fallback"}

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: "*"
plugins:
  - serverless-offline
