# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rootxploiter
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-node-express
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
plugins:
  - serverless-offline
